language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
  - "nightly"

install:
  - pip install --upgrade pytest setuptools
  - pip install --editable .
  - pip install -r tests/requirements.txt

script:
  - pytest

notifications:
  email: false
