import typing as t

def get_data(
    session: t.Text | None = ...,
    day: int | None = ...,
    year: int | None = ...,
    block: bool | t.Literal["q"] = ...,
) -> t.Text: ...
def most_recent_year() -> int: ...
def current_day() -> int: ...
def get_day_and_year() -> tuple[int, int]: ...
